//
//  DesignSystemProvenance.swift
//  HomeRec
//
//  GENERATED by scripts/design-system/sync.sh — do not hand-edit.
//
//  Records where `DesignSystem/Vendor/` came from. The commit says *when* we
//  synced; the per-file blob SHAs say *what*, file by file. The blob SHAs are the
//  load-bearing part: the vendored paths differ from upstream's
//  (`DesignSystem/Vendor/Tokens/X.swift` here vs
//  `design-system/Sources/GlassKit/Tokens/X.swift` there), so `git diff` cannot
//  compare the two trees directly. A blob SHA is path-independent, so it can.
//
//  `scripts/design-system/check-vendor-drift.sh` re-derives each file's hash and
//  compares. Any mismatch means a vendored file was edited, which is the one
//  failure mode that silently destroys the ability to re-sync.
//
//  This type is app-owned, so it deliberately does NOT take the `Glass` prefix —
//  that prefix is reserved for vendored upstream code, and the distinction is
//  what makes "is this file ours?" answerable from the type name alone.
//

import Foundation

enum DesignSystemProvenance {

    static let sourceRepo = "https://github.com/melissa-pereira-deel/ui-explorations"
    static let branch = "explore/concept-prototypes"
    static let commit = "a41df5b97de7c679d077bfc2f8158c7c8b48f281"
    static let syncedAt = "2026-08-06"

    /// Upstream path prefix the vendored tree mirrors.
    static let upstreamPrefix = "design-system/Sources/GlassKit"

    /// Vendored path (relative to `DesignSystem/Vendor/`) → upstream git blob SHA.
    static let blobs: [String: String] = [
        "Components/GlassTimecode.swift": "c2fc9d7549b676a992005223f93e59902683a163",
        "Components/GlassWaveform.swift": "c41873ede93587f61fcfe28c630dc5692092555a",
        "Primitives/GlassBrandMark.swift": "118cda52215dc212a55512b0255e932daedde611",
        "Primitives/GlassChip.swift": "d0aa2ca6b6aa2f0f9ffd7244d63f321b4ca66591",
        "Primitives/GlassHover.swift": "3b1aa1113b330ee19e98167bee70903a662af4ce",
        "Primitives/GlassIconButton.swift": "385a6ff59495e229d129fa6a1bcc0e3cfe0e2999",
        "Primitives/GlassLabels.swift": "300447e211940efaa81f535d5d3ddf77969e1568",
        "Primitives/GlassPillButton.swift": "71d75c4dae5aef36b1f15958348d6532a31b6114",
        "Primitives/GlassPreviewStage.swift": "d4f4969976cc1fc7c167cd3080b1f965fe971cb9",
        "Primitives/GlassSurface.swift": "ed4d371c0528eac23afc492318b7116b670c7c98",
        "Tokens/GlassBackdrop.swift": "938c4ff21e020a9fe350f696e52a7e2db3f58980",
        "Tokens/GlassColors.swift": "07f57079914b1d76c1ed51ad212218f0d611583e",
        "Tokens/GlassElevation.swift": "a18ca731cc03dc2e933a280611822b02abcc5d5c",
        "Tokens/GlassMetrics.swift": "4855a1a9152875ba1ec5cfdff52cc1349712c85b",
        "Tokens/GlassMotion.swift": "f900a3da274142e84427e224367f93f481c25600",
        "Tokens/GlassTheme.swift": "e4203742738c7cabc4b05ce3a4e0e466a7bdea9b",
        "Tokens/GlassTypography.swift": "db0d18f5e26d71c82040704b9e7db43f9d8232f1",
    ]

    /// Files carrying a recorded local patch → the hash they should have *after*
    /// it is applied.
    ///
    /// Recording the post-patch hash rather than re-deriving it keeps the drift
    /// check working offline, with no upstream objects present. The patch itself
    /// lives in `scripts/design-system/patches/` and is what a future re-sync
    /// replays; `blobs` above still holds the pristine upstream hash, so the
    /// three-way relationship stays reconstructable.
    ///
    /// **Target: empty.** Each entry is a file that no longer diffs cleanly
    /// against upstream. At three, vendoring has stopped paying for itself —
    /// see docs/design-system-vendoring.md.
    static let patchedBlobs: [String: String] = [
        // The focus ring read as a permanent border on the record control.
        "Primitives/GlassPillButton.swift": "4572b62a2faac301e73794446ee54669580b222d",
    ]
}
