#!/usr/bin/env bash
#
# Re-vendor the GlassKit design-system files from ui-explorations, and regenerate
# DesignSystemProvenance.swift.
#
# The two repos share history — ui-explorations branched from home-rec — so
# adding it as a remote costs almost nothing: the fetch transfers only the
# design-system objects, everything else is already in the object store. It also
# pins those objects locally, which is the point: the vendored source stays
# re-syncable even if the design repo is force-pushed or archived.
#
#   ./scripts/design-system/sync.sh              # sync to the branch head
#   ./scripts/design-system/sync.sh <commit-ish> # sync to a specific commit
#
# This OVERWRITES everything under DesignSystem/Vendor/. That is intended — those
# files are not ours to edit. Local changes live in DesignSystem/Adapters/.
# Run check-vendor-drift.sh first if you are unsure whether anything drifted.

set -uo pipefail
cd "$(dirname "$0")/../.." || exit 1

REMOTE="ui-explorations"
REMOTE_URL="https://github.com/melissa-pereira-deel/ui-explorations"
BRANCH="explore/concept-prototypes"
UPSTREAM_PREFIX="design-system/Sources/GlassKit"
VENDOR_DIR="HomeRec/HomeRec/DesignSystem/Vendor"
PROVENANCE="HomeRec/HomeRec/DesignSystem/DesignSystemProvenance.swift"

# The vendored set, deliberately minimal. Adding to this list is a scope
# decision, not a mechanical one: every extra file is surface area to re-sync.
# Notably absent — the Patterns layer, TransportMachine, GlassTransportState /
# GlassTransportControl, GlassNotice, take rows, the player, the scrubber, the
# filter bar, and the gallery. Importing the kit's *state* vocabulary would
# duplicate RecordingState, which the app already owns and tests.
FILES=(
    "Tokens/GlassColors.swift"
    "Tokens/GlassTypography.swift"
    "Tokens/GlassMetrics.swift"
    "Tokens/GlassMotion.swift"
    "Tokens/GlassTheme.swift"
    "Tokens/GlassBackdrop.swift"
    "Tokens/GlassElevation.swift"
    "Primitives/GlassSurface.swift"
    "Primitives/GlassBrandMark.swift"
    "Primitives/GlassPillButton.swift"
    "Primitives/GlassChip.swift"
    "Primitives/GlassLabels.swift"
    "Primitives/GlassIconButton.swift"
    "Primitives/GlassHover.swift"
    "Primitives/GlassPreviewStage.swift"
    "Components/GlassWaveform.swift"
    # Not used directly by the app, but GlassWaveform needs its
    # `Double.clampedToUnitInterval`. Taking the whole file is the rule: a
    # hand-written duplicate of that extension would collide the moment anyone
    # vendors GlassTimecode properly.
    "Components/GlassTimecode.swift"
)

git remote get-url "$REMOTE" >/dev/null 2>&1 || {
    echo "Adding remote $REMOTE…"
    git remote add "$REMOTE" "$REMOTE_URL" || exit 1
}

echo "Fetching $REMOTE/$BRANCH…"
git fetch "$REMOTE" "$BRANCH" || exit 1

REF="${1:-$REMOTE/$BRANCH}"
commit=$(git rev-parse "$REF") || exit 1
echo "Syncing to $commit"
echo

for rel in "${FILES[@]}"; do
    dest="$VENDOR_DIR/$rel"
    mkdir -p "$(dirname "$dest")"
    if ! git show "$commit:$UPSTREAM_PREFIX/$rel" > "$dest"; then
        echo "  ✗ $rel — not found upstream at $commit"
        exit 1
    fi
    printf '  ✓ %s\n' "$rel"
done

echo
echo "Regenerating $PROVENANCE…"

{
    cat <<'HEADER'
//
//  DesignSystemProvenance.swift
//  HomeRec
//
//  GENERATED by scripts/design-system/sync.sh — do not hand-edit.
//
//  Records where `DesignSystem/Vendor/` came from. The commit says *when* we
//  synced; the per-file blob SHAs say *what*, file by file. The blob SHAs are the
//  load-bearing part: the vendored paths differ from upstream's
//  (`DesignSystem/Vendor/Tokens/X.swift` here vs
//  `design-system/Sources/GlassKit/Tokens/X.swift` there), so `git diff` cannot
//  compare the two trees directly. A blob SHA is path-independent, so it can.
//
//  `scripts/design-system/check-vendor-drift.sh` re-derives each file's hash and
//  compares. Any mismatch means a vendored file was edited, which is the one
//  failure mode that silently destroys the ability to re-sync.
//
//  This type is app-owned, so it deliberately does NOT take the `Glass` prefix —
//  that prefix is reserved for vendored upstream code, and the distinction is
//  what makes "is this file ours?" answerable from the type name alone.
//

import Foundation

enum DesignSystemProvenance {

HEADER
    printf '    static let sourceRepo = "%s"\n' "$REMOTE_URL"
    printf '    static let branch = "%s"\n' "$BRANCH"
    printf '    static let commit = "%s"\n' "$commit"
    printf '    static let syncedAt = "%s"\n' "$(date -u +%Y-%m-%d)"
    echo
    echo '    /// Upstream path prefix the vendored tree mirrors.'
    printf '    static let upstreamPrefix = "%s"\n' "$UPSTREAM_PREFIX"
    echo
    echo '    /// Vendored path (relative to `DesignSystem/Vendor/`) → upstream git blob SHA.'
    echo '    static let blobs: [String: String] = ['
    for rel in $(printf '%s\n' "${FILES[@]}" | sort); do
        printf '        "%s": "%s",\n' "$rel" "$(git hash-object "$VENDOR_DIR/$rel")"
    done
    echo '    ]'
    echo '}'
} > "$PROVENANCE"

echo
echo "Done. Review the diff, rebuild, and re-run the test suite."
echo "Upstream changes since the previous sync:"
echo "  git diff <previous-commit>..$commit -- $UPSTREAM_PREFIX/"
